services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 88:80
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7.2.5-alpine
    container_name: redis-server